[package]
name = "advent2020"
version = "0.1.0"
authors = ["william <wi.alhant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"

[[bin]]
name = "day01"
path = "src/days/day01.rs"

[[bin]]
name = "day02"
path = "src/days/day02.rs"

[[bin]]
name = "day03"
path = "src/days/day03.rs"